version: '3.8'

services:
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    depends_on:
      - database

  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'rentalx'
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
